spring:
  application:
    name: payment-simulator
  datasource:
    url: ${DB_URL:jdbc:h2:mem:payments}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS:org.h2.Driver}
  jpa:
    open-in-view: false
  mvc.servlet.path: /api
  threads.virtual.enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - retryevents
          - retries
          - bulkheads
          - bulkheadevents


resilience4j:
  retry:
    instances:
      transaction-service:
        # Maximum number of attempts (including the initial call as the first attempt)
        max-attempts: 3
        # Fixed wait duration between retry attempts
        wait-duration: 1s
        ignore-exceptions:
          - pl.varlab.payment.common.ValidationException

  bulkhead:
    configs:
      default:
        max-concurrent-calls: 5
    instances:
      transaction-controller:
        max-concurrent-calls: 2

springdoc:
  show-actuator: true
  api-docs.path: /api-docs

logging:
  file:
    name: logs/payments-simulator.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 90
      total-size-cap: 10GB
      clean-history-on-start: false
  level:
    pl.varlab.payment: info