spring:
  application:
    name: payment-simulator
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  mvc.servlet.path: /api

# TODO: enable actuator
resilience4j.retry:
  instances:
    transaction-service:
      # Maximum number of attempts (including the initial call as the first attempt)
      max-attempts: 3
      # Fixed wait duration between retry attempts
      wait-duration: 1s


logging:
  file:
    name: logs/payments-simulator.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 90
      total-size-cap: 10GB
      clean-history-on-start: false
  level:
    pl.varlab.payment: info